workflow_name1:
    algorithm: 'x'
    summary: 'criticality'
    samples:
    - 'Coursework3\original_code\data1.csv'
    - 'Coursework3\original_code\data2.csv'
    weights: 'Coursework3\original_code\weights.csv'

workflow_name2:
    algorithm: 'y'
    summary: 'criticality'
    samples:
    - 'Coursework3\original_code\data1.csv'
    - 'Coursework3\original_code\data2.csv'
    weights: 'Coursework3\original_code\weights.csv'

workflow_name3:
    algorithm: 'x'
    summary: 'd'
    samples:
    - 'Coursework3\original_code\data1.csv'
    - 'Coursework3\original_code\data2.csv'
    weights: 'Coursework3\original_code\weights.csv'
    
workflow_name4:
    algorithm: 'y'
    summary: 'd'
    samples:
    - 'Coursework3\original_code\data1.csv'
    - 'Coursework3\original_code\data2.csv'
    weights: 'Coursework3\original_code\weights.csv'